In [1]:
import numpy as np
import pandas as pd
import pickle
import random
# SQL related packages
from sqlalchemy import create_engine
from sqlalchemy_utils import database_exists, create_database
import psycopg2
# sklearn packages
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics, preprocessing
from sklearn.linear_model import LogisticRegression as Log
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict, GridSearchCV
# text analysis packages
from nltk import word_tokenize
from nltk.corpus import stopwords
import string
from collections import Counter
from nltk.stem.porter import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer

import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

#### Load the non-text data

In [2]:
# read the data with the non-text features
patents = pd.read_pickle("patent_data/nontext_features.p")

In [3]:
print patents.shape
patents.head()

(12030, 16)


id  publication_year  B  C  D  E  F  G  H  num_applications  \
0  US6699658B1              2004  0  1  0  0  0  0  0                 5   
1  US6699724B1              2004  0  0  0  0  0  1  0                32   
2  US6690816B2              2004  0  0  0  0  0  1  0                 8   
3  US6711436B1              2004  0  0  0  0  0  0  0                 4   
4  US6711432B1              2004  0  0  0  0  0  0  0                 7   

   num_patent_citations  num_nonpatent_citations  num_claims  num_similar_doc  \
0                    28                       34          42                1   
1                    47                       44          25                0   
2                     9                        0          32                1   
3                   105                      109          45                7   
4                    15                      114          44                3   

   num_authors  payment_times  
0            4              3  
1            4              3  
2            4              1  
3            1              3  
4            4              3

#### Format the data

In [4]:
# reformat the response variable into binary
y_data = np.zeros(patents.shape[0])
y_data[patents['payment_times'].values >= 2] = 1

print "Percentage of patents with > 1 maintenance fee payments: ", np.mean(y_data)

Percentage of patents with > 1 maintenance fee payments:  0.62859517872


In [5]:
# predictors
x_data = patents.drop(['id', 'payment_times', 'publication_year'], axis = 1).values
x_data.shape

(12030, 13)

#### Load claims data

In [6]:
#access to sql database
dbname = 'patent_db'
username = 'jy'
pswd = 'jy'

engine = create_engine('postgresql://%s:%s@localhost/%s'%(username,pswd,dbname))

# reading from sql database
# connect:
con = None
con = psycopg2.connect(database = dbname, user = username, host='localhost', password=pswd)

In [7]:
# read data from 2004-2007
years = np.arange(2004, 2008)

# dataframe to store the results
claims = pd.DataFrame()

# import the abstract from each table
for year in years:
    # query:
    sql_query = """
    SELECT claims, id, payment_times, classification
        FROM patents_%s;
    """ %str(year)

    results = pd.read_sql_query(sql_query,con)
    
    claims = pd.concat([claims, results], axis = 0)
    
# check size of the data
claims.shape

(12033, 4)

In [8]:
# remove the patents missing classification data
missing_class_index = (claims['classification'].values == 'NA')

# reassign patent index
claims.index = range(len(claims.index))
# drop the rows
claims =  claims.drop(patents.index[missing_class_index])
claims.shape

/home/jy/anaconda2/envs/my_projects_env/lib/python2.7/site-packages/pandas/indexes/base.py:1434: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 12030 but corresponding boolean dimension is 12033
  result = getitem(key)


(12030, 4)

In [9]:
def tokenize_cleaning(text):
    # tokenize the text first
    tokens = word_tokenize(text.decode('utf-8'))
    
    # lowercase all the words
    tokens = [w.lower() for w in tokens]
    
    # clean up stop words and punctuations 
    stop_list = stopwords.words('english') + list(string.punctuation)

    tokens_no_stop = [token for token in tokens
                        if token not in stop_list]            
    
#     # extract stem of the words
#     stemmer = PorterStemmer()
#     tokens_stem = [stemmer.stem(token) for token in tokens_no_stop]

    # use lemma instead
    # reason: remove the influence of plural or tense
    # but retain the subtle difference in legal writting
    lemmatizer = WordNetLemmatizer()
    tokens_lemma = [lemmatizer.lemmatize(token) for token in tokens_no_stop]
    
    # remove numbers (the actual values are not useful)
    tokens_no_num = []
    for token in tokens_lemma:
        try:
            float(token)
        except:
            tokens_no_num.append(token)
    
    return tokens_no_num

In [10]:
# tokenize_clean the claims and count the occurence of the words

cleaned_text = []
for i in range(claims.shape[0]):
    tokens = tokenize_cleaning(claims['claims'].iloc[i])
    cleaned_text.append(' '.join(word for word in tokens))

In [11]:
# convert to bag-of-words
# min number selected by examining the low-frequency words
vectorizer = CountVectorizer(max_df = 0.4, min_df=5)

# perform a count-based vectorization of the document
word_vec = vectorizer.fit(cleaned_text)
word_counts = word_vec.transform(cleaned_text)

# convert to array
word_counts = word_counts.toarray()
word_counts.shape

(12030, 8034)

In [12]:
# still need to remove some number words 
# due to how CountVectorizer treats '-' and '/'

# remove any word with numbers in it
words = word_vec.get_feature_names()
num_word_index = np.zeros(len(words))

for i in range(len(words)):
    word = words[i]
    for j in range(len(word)):
        try:
            float(word[j])
            num_word_index[i] = 1
            break
        except:
            continue
        
print "Number of numerical words detected: ", int(np.sum(num_word_index))

# remove the number words
words_no_num = np.asarray(words)[num_word_index == 0]
word_counts = word_counts[:, num_word_index == 0]

word_counts.shape

Number of numerical words detected:  222


(12030, 7812)

In [13]:
# combine the claims data with the non-text features
x_data = np.concatenate([x_data, word_counts], axis = 1)

In [14]:
# split train and test sets
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, 
                                                    test_size = 0.2, 
                                                    random_state = 123)

print "Dataset dimensions:"
print "x_train: ", x_train.shape
print "x_test: ", x_test.shape
print "y_train: ", y_train.shape
print "y_test: ", y_test.shape

Dataset dimensions:
x_train:  (9624, 7825)
x_test:  (2406, 7825)
y_train:  (9624,)
y_test:  (2406,)


### Using subsampling to generate balanced training data

In [18]:
### subsampling the training data
# sample the same number of'useful' patents as the 'not useful' patents
# size of each class
num_size = np.sum(y_train == 0)

#random shuffle the rows
n = x_train.shape[0]
perm = range(n)
np.random.shuffle(perm)

x_train = x_train[perm]
y_train = y_train[perm]

# separate the two classes
x_useful = x_train[y_train == 1, :]
x_not_useful = x_train[y_train == 0, :]
y_useful = y_train[y_train == 1]
y_not_useful = y_train[y_train == 0]

# sample num_size from the 'useful' class
x_useful = x_useful[:num_size]
y_useful = y_useful[:num_size]

# combine the two classes
x_train_sub = np.concatenate((x_useful, x_not_useful), axis = 0)
y_train_sub = np.concatenate((y_useful, y_not_useful), axis = 0)

# shuffle again
# shuffle the combined data
n2 = x_train_sub.shape[0]
perm2 = range(n2)
np.random.shuffle(perm2)

x_train_sub = x_train_sub[perm2]
y_train_sub = y_train_sub[perm2]

# check the size
print x_train_sub.shape
print y_train_sub.shape

(7198, 7825)
(7198,)


In [19]:
# standardize the predictors
scaler = preprocessing.StandardScaler()

x_train_std = scaler.fit_transform(x_train_sub)
x_test_std = scaler.transform(x_test)

/home/jy/anaconda2/envs/my_projects_env/lib/python2.7/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


#### PCA on the claims word-counts

In [20]:
# try dimensionality reduction using PCA
pca = PCA()

x_train_counts_pca = pca.fit_transform(x_train_std[:, 13:])
x_test_counts_pca = pca.transform(x_test_std[:, 13:])

In [21]:
# find the cum-variance explained at each level
total_var = np.cumsum(pca.explained_variance_ratio_)
n_pc = np.where((total_var > 0.9) == True)[0][0]

print "The number of PCs that can explain > 90% variability: ", n_pc

The number of PCs that can explain > 90% variability:  2425


In [24]:
# combine to the non-text features
x_train_pca = np.concatenate([x_train_std[:, :13], x_train_counts_pca[:, :n_pc]], axis = 1)
x_test_pca = np.concatenate([x_test_std[:, :13], x_test_counts_pca[:, :n_pc]], axis = 1)

### Model training
#### Logistic Regression

In [26]:
### use logistic regression

# call the model function
model = Log()
# parameter tuning
c =  np.logspace(-5, 5, 11)

# use grid search with 5-fold CV
grid_model = GridSearchCV(model, param_grid = {'C': c}, cv  = 5, scoring = 'accuracy')
# fit on the data
grid_model.fit(x_train_pca, y_train_sub) 

In [27]:
# check results
print "Best accuracy:", grid_model.best_score_
print "Best parameter: ", grid_model.best_params_

Best accuracy: 0.564184495693
Best parameter:  {'C': 0.0001}


In [29]:
# check confusion matrix
best_log = grid_model.best_estimator_
best_log.fit(x_train_pca, y_train_sub)

y_pred = best_log.predict(x_test_pca)

# accuracy
print "Test accuracy: ", np.mean(y_pred == y_test)
print "F1 score: ", metrics.f1_score(y_test, y_pred)
print "Precision: ", metrics.precision_score(y_test, y_pred)
print "Recall: ", metrics.recall_score(y_test, y_pred)
metrics.confusion_matrix(y_test, y_pred)

Test accuracy:  0.536575228595
F1 score:  0.552747693542
Precision:  0.720711297071
Recall:  0.448275862069


array([[602, 267],
       [848, 689]])

In [48]:
model = Log()

# parameter tuning
c =  np.logspace(-5, 3, 9)

# add class weight tuning to the random forest model
weights = np.logspace(-4,0,5)
weight_list_dict = [{0:1, 1: weights[i]} for i in range(len(weights))]

# use grid search with 5-fold CV
grid_model = GridSearchCV(model, param_grid = {'C': c,'class_weight': weight_list_dict}, 
                          cv  = 5, scoring = 'f1')
# fit on the data
grid_model = grid_model.fit(x_train_pca, y_train_sub)

In [49]:
# check results
print "Best accuracy:", grid_model.best_score_
print "Best parameter: ", grid_model.best_params_

Best accuracy: 0.528970792818
Best parameter:  {'C': 1.0, 'class_weight': {0: 1, 1: 1.0}}


In [50]:
# check confusion matrix
best_log = grid_model.best_estimator_
best_log.fit(x_train_pca, y_train_sub)

y_pred = best_log.predict(x_test_pca)

# accuracy
print "Test accuracy: ", np.mean(y_pred == y_test)
print "F1 score: ", metrics.f1_score(y_test, y_pred)
print "Precision: ", metrics.precision_score(y_test, y_pred)
print "Recall: ", metrics.recall_score(y_test, y_pred)
metrics.confusion_matrix(y_test, y_pred)

Test accuracy:  0.540315876974
F1 score:  0.586077844311
Precision:  0.68986784141
Recall:  0.509433962264


array([[517, 352],
       [754, 783]])

#### Random Forest

In [30]:
### tune random forest

model = RandomForestClassifier(n_estimators = 100)

# tune max_features
param_space = np.arange(2, 14, 2)

grid_model = GridSearchCV(model, n_jobs = 4, 
                          param_grid = {'max_features': param_space}, 
                          cv  = 5, scoring = 'accuracy')
# fit on the data
grid_model = grid_model.fit(x_train_pca, y_train_sub)

In [31]:
# check results
print "Best accuracy:", grid_model.best_score_
print "Best parameter: ", grid_model.best_params_

Best accuracy: 0.550708530147
Best parameter:  {'max_features': 2}


In [32]:
# check confusion matrix
best_rf = grid_model.best_estimator_
best_rf.fit(x_train_pca, y_train_sub)

y_pred = best_rf.predict(x_test_pca)

# accuracy
print "Test accuracy: ", np.mean(y_pred == y_test)
print "F1 score: ", metrics.f1_score(y_pred, y_test)
print "Precision: ", metrics.precision_score(y_pred, y_test)
print "Recall: ", metrics.recall_score(y_pred, y_test)
metrics.confusion_matrix(y_test, y_pred)

Test accuracy:  0.531587697423
F1 score:  0.580573129885
Precision:  0.507482108003
Recall:  0.678260869565


array([[499, 370],
       [757, 780]])

In [51]:
# tuning class weight
model = RandomForestClassifier(n_estimators = 100)

# tune max_features
param_space = np.arange(2, 10, 2)

# add class weight tuning to the random forest model
weights = np.logspace(-4,0,5)
weight_list_dict = [{0:1, 1: weights[i]} for i in range(len(weights))]

grid_model = GridSearchCV(model, n_jobs = 4, 
                          param_grid = {'max_features': param_space,
                                       'class_weight': weight_list_dict}, 
                          cv  = 5, scoring = 'f1')
# fit on the data
grid_model = grid_model.fit(x_train_pca, y_train_sub)

In [52]:
# check results
print "Best accuracy:", grid_model.best_score_
print "Best parameter: ", grid_model.best_params_

Best accuracy: 0.600771935735
Best parameter:  {'max_features': 8, 'class_weight': {0: 1, 1: 0.001}}


In [53]:
# check confusion matrix
best_rf = grid_model.best_estimator_
best_rf.fit(x_train_pca, y_train_sub)

y_pred = best_rf.predict(x_test_pca)

# accuracy
print "Test accuracy: ", np.mean(y_pred == y_test)
print "F1 score: ", metrics.f1_score(y_test, y_pred)
print "Precision: ", metrics.precision_score(y_test, y_pred)
print "Recall: ", metrics.recall_score(y_test, y_pred)
metrics.confusion_matrix(y_test, y_pred)

Test accuracy:  0.548628428928
F1 score:  0.626033057851
Precision:  0.664959765911
Recall:  0.591411841249


array([[411, 458],
       [628, 909]])

In [54]:
# pickle the rf model
pickle.dump(best_rf, open("models/best_rf_combined.p", 'wb'))

In [55]:
# pickle the pca and scaler
pickle.dump(pca, open("models/best_rf_pca.p", 'wb'))
pickle.dump(scaler, open("models/best_rf_scaler.p", 'wb'))

In [41]:
## try open the model and predict
#rf = pickle.load(open("models/best_rf.p", 'r'))

### Directly work on the imbalanced training data + tune class weight

In [15]:
# standardize the predictors
scaler = preprocessing.StandardScaler()

x_train_std = scaler.fit_transform(x_train)
x_test_std = scaler.transform(x_test)

/home/jy/anaconda2/envs/my_projects_env/lib/python2.7/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


In [16]:
# try dimensionality reduction using PCA
pca = PCA()

x_train_counts_pca = pca.fit_transform(x_train_std[:, 13:])
x_test_counts_pca = pca.transform(x_test_std[:, 13:])

In [17]:
# find the cum-variance explained at each level
total_var = np.cumsum(pca.explained_variance_ratio_)
n_pc = np.where((total_var > 0.9) == True)[0][0]

print "The number of PCs that can explain > 90% variability: ", n_pc

The number of PCs that can explain > 90% variability:  2797


In [18]:
# combine to the non-text features
x_train_pca = np.concatenate([x_train_std[:, :13], x_train_counts_pca[:, :n_pc]], axis = 1)
x_test_pca = np.concatenate([x_test_std[:, :13], x_test_counts_pca[:, :n_pc]], axis = 1)

In [19]:
# Random Forest + tuning class weight
model = RandomForestClassifier(n_estimators = 100)

# tune max_features
param_space = np.arange(2, 8, 2)

# add class weight tuning to the random forest model
weights = np.logspace(-8,0,9)
weight_list_dict = [{0:1, 1: weights[i]} for i in range(len(weights))]

grid_model = GridSearchCV(model, n_jobs = 4, 
                          param_grid = {'max_features': param_space,
                                       'class_weight': weight_list_dict}, 
                          cv  = 5, scoring = 'f1')
# fit on the data
grid_model = grid_model.fit(x_train_pca, y_train)

In [20]:
# check results
print "Best accuracy:", grid_model.best_score_
print "Best parameter: ", grid_model.best_params_

Best accuracy: 0.768468109077
Best parameter:  {'max_features': 2, 'class_weight': {0: 1, 1: 1.0000000000000001e-05}}


In [21]:
# check confusion matrix
best_rf = grid_model.best_estimator_
best_rf.fit(x_train_pca, y_train)

y_pred = best_rf.predict(x_test_pca)

# accuracy
print "Test accuracy: ", np.mean(y_pred == y_test)
print "F1 score: ", metrics.f1_score(y_test, y_pred)
print "Precision: ", metrics.precision_score(y_test, y_pred)
print "Recall: ", metrics.recall_score(y_test, y_pred)
metrics.confusion_matrix(y_test, y_pred)

Test accuracy:  0.644222776392
F1 score:  0.776384535005
Precision:  0.648625054561
Recall:  0.966818477554


array([[  64,  805],
       [  51, 1486]])