In [47]:
import numpy as np
import pandas as pd
import pickle
import random
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression as Log
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_predict

#### Load the data

In [2]:
# read the data with the non-text features
patents = pd.read_pickle("patent_data/nontext_features.p")

In [3]:
print patents.shape
patents.head()

(12033, 17)


id  publication_year  B  C  D  E  F  G  H  NA  num_applications  \
0  US6699658B1              2004  0  1  0  0  0  0  0   0                 5   
1  US6699724B1              2004  0  0  0  0  0  1  0   0                32   
2  US6690816B2              2004  0  0  0  0  0  1  0   0                 8   
3  US6711436B1              2004  0  0  0  0  0  0  0   0                 4   
4  US6711432B1              2004  0  0  0  0  0  0  0   0                 7   

   num_patent_citations  num_nonpatent_citations  num_claims  num_similar_doc  \
0                    28                       34          42                1   
1                    47                       44          25                0   
2                     9                        0          32                1   
3                   105                      109          45                7   
4                    15                      114          44                3   

   num_authors  payment_times  
0            4              3  
1            4              3  
2            4              1  
3            1              3  
4            4              3

#### Format the data

In [12]:
# reformat the response variable into binary
y_data = np.zeros(patents.shape[0])
y_data[patents['payment_times'].values >= 2] = 1

print "Percentage of patents with > 1 maintenance fee payments: ", np.mean(y_data)

Percentage of patents with > 1 maintenance fee payments:  0.628521565694


In [34]:
# predictors
x_data = patents.drop(['id', 'payment_times'], axis = 1).values
x_data.shape

(12033, 15)

In [35]:
# split train and test sets
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, 
                                                    test_size = 0.2, 
                                                    random_state = 123)

print "Dataset dimensions:"
print "x_train: ", x_train.shape
print "x_test: ", x_test.shape
print "y_train: ", y_train.shape
print "y_test: ", y_test.shape

Dataset dimensions:
x_train:  (9626, 15)
x_test:  (2407, 15)
y_train:  (9626,)
y_test:  (2407,)


In [55]:
# percentage of 1's in the response variable
np.mean(y_data == 1)

0.62852156569434059

### Model training
#### Basic Logistic Regression

In [38]:
### use logistic regression

# call the model function
model = Log()
# parameter tuning
c =  np.logspace(-5, 5, 11)

# use grid search with 5-fold CV
grid_model = GridSearchCV(model, param_grid = {'C': c}, cv  = 5, scoring = 'accuracy')
# fit on the data
grid_model = grid_model.fit(x_train, y_train) 

In [43]:
# check results
print "Best accuracy:", grid_model.best_score_
print "Best parameter: ", grid_model.best_params_

Best accuracy: 0.630895491378
Best parameter:  {'C': 0.10000000000000001}


In [48]:
# check confusion matrix
best_log = grid_model.best_estimator_
y_pred = cross_val_predict(best_log, x_train, y_train, cv = 5)

metrics.confusion_matrix(y_train, y_pred)

array([[  75, 3493],
       [  60, 5998]])

#### Logistic Regression with Balanced Weight

In [53]:
# call the model function with balanced weight
model = Log(class_weight='balanced')
# parameter tuning
c =  np.logspace(-5, 5, 11)

# use grid search with 5-fold CV
grid_model = GridSearchCV(model, param_grid = {'C': c}, cv  = 5, scoring = 'accuracy')
# fit on the data
grid_model = grid_model.fit(x_train, y_train) 

In [54]:
# check results
print "Best accuracy:", grid_model.best_score_
print "Best parameter: ", grid_model.best_params_

# check confusion matrix
best_log = grid_model.best_estimator_
y_pred = cross_val_predict(best_log, x_train, y_train, cv = 5)

metrics.confusion_matrix(y_train, y_pred)

Best accuracy: 0.551734884687
Best parameter:  {'C': 0.10000000000000001}


array([[2110, 1458],
       [2857, 3201]])

#### Random Forest

In [50]:
### tune random forest

model = RandomForestClassifier(n_estimators = 50)

# tune max_features
param_space = np.arange(2, 15, 2)

grid_model = GridSearchCV(model, n_jobs = 4, 
                          param_grid = {'max_features': param_space}, 
                          cv  = 5, scoring = 'accuracy')
# fit on the data
grid_model = grid_model.fit(x_train, y_train)

In [52]:
# check results
print "Best accuracy:", grid_model.best_score_
print "Best parameter: ", grid_model.best_params_

Best accuracy: 0.613338873883
Best parameter:  {'max_features': 2}


In [51]:
# check confusion matrix
best_rf = grid_model.best_estimator_
y_pred = cross_val_predict(best_rf, x_train, y_train, cv = 5)

metrics.confusion_matrix(y_train, y_pred)

array([[ 846, 2722],
       [1029, 5029]])